### ISSUE TITLE
TODO on how to transit smoothly

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/news-for-maintainers#1]
##### SUMMARY
Relates to https://github.com/ansible-community/community-topics/issues/51

TODO on how to transit smoothly:

- [x] 1. Permissions. Everyone can create issues or only certain folks? We could start with everyone, then will see.
- [x] 2. Fill up README describing the purpose of the repo.
- [x] 3. Ask people in the Changes Impacting [issue](https://github.com/ansible-collections/overview/issues/45) to subscribe to this repo in advance.
- [x] 4. Create issues in all collection repos here + 3d party collections + ~~ansible/ansible~~ with the announcement about this repo asking to subscribe (don't forget to mention Bullhorn and other stuff there).
- [x] 5. Announce via Bullhorn.
- [x] 6. Announce in Community meeting.
- [x] 7. Put a final comment in in the Changes Impacting [issue](https://github.com/ansible-collections/overview/issues/45) and to its description that will say that the issue is no longer used redirecting folks to this repo.
- [x] 8. Lock the conversation in the Changes Impacting [issue](https://github.com/ansible-collections/overview/issues/45).
- [x] 9. Report in the [Community topic](https://github.com/ansible-community/community-topics/issues/51) and close it.
- [ ] 10. (Optional) Think of possible labels for issues based on the history in the Changes Impacting [issue](https://github.com/ansible-collections/overview/issues/45), create a list.

**Comment by Andersson007** [comment]
@gundalow @tadeboro @felixfontein @briantist @sivel @mattclay 
Anything else we should add to the TODO to make the move as smooth as possible? (please don't create the issues here before everything is done. I'll inform everyone directly).

**Comment by Andersson007** [comment]
to complete p. 2, created https://github.com/ansible-collections/news-for-maintainers/pull/2

**Comment by briantist** [comment]
The list looks very comprehensive to me, and I think it's fine to just get started on it and iterate as we go if we find there are additional items needed or changes to the current list.

**Comment by Andersson007** [comment]
@tadeboro @briantist @felixfontein (i saw your thumb-ups) thanks for your feedback on the TODO! Cool, will start on Monday

**Comment by Andersson007** [comment]
So, at the moment:
p. 1. ` 1. Permissions. Everyone can create issues or only certain folks? We could start with everyone, then will see.` - OK, if no objections, we'll start with just the default permissions for the public repo, then will adjust if needed.
p. 2 `Fill up README describing the purpose of the repo.` - If no objections, I'll merge https://github.com/ansible-collections/news-for-maintainers/pull/2 on Monday and will go further.

**Comment by Andersson007** [comment]
Done
